### ISSUE TITLE
Do not update to a tool's latest version if it is a pre-release 

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/setup-purescript#10]
The 'latest' flag for this library should only support [normal semantic versions](https://semver.org/#spec-item-2), which means `X.Y.Z`. However, right now it will pull whatever the latest release is from GitHub, which might be a [pre-release version](https://semver.org/#spec-item-9) or contain [build metadata](https://semver.org/#spec-item-10).

In the `UpdateVersions` script, all we do is check that the version is valid according to the [`versions` library](https://github.com/hdgarrood/purescript-versions):

https://github.com/purescript-contrib/setup-purescript/blob/beee57d7ab2ed828393646fccc002b1476e906c2/src/Setup/UpdateVersions.purs#L87-L95

In this check we should additionally ensure that the version doesn't contain any pre-release ~or build identifiers~. The `versions` library includes that information in its type, so this should be possible:

https://github.com/hdgarrood/purescript-versions/blob/5da24cc63a1fa9a3d09156afa49ad49b3c0fff84/src/Data/Version.purs#L54-L56

This will prevent users from inadvertently updating to an alpha or pre-release version that they almost certainly don't want. They can still point to that version by specifying the version manually.

**Comment by Thimoteus** [comment]
Is this just checking that both `List Identifier`s are empty?

**Comment by thomashoneyman** [comment]
I believe so -- the `versions` library may have helpers for this as well.

**Comment by hdgarrood** [comment]
I think the function we want is `isPreRelease`: https://github.com/hdgarrood/purescript-versions/blob/v5.0.1/src/Data/Version.purs#L173-L173. That is, we should be checking that the first list (the prerelease identifiers, the part after a `-`) is empty, but technically we should be ignoring the second. The build metadata (stuff which follows a `+`) doesn't indicate that it's not a proper version, it's just a place you can store something like a hash or a date if you want to do that. It's unlikely to make much a difference though, since barely anyone uses build metadata anyway.

**Comment by thomashoneyman** [comment]
If we can do the right thing (only check pre-release), then we should! Thanks for pointing that out. I've edited the original issue description to only focus on pre-release information, and not on build metadata.

**Comment by triallax** [comment]
I'd like to give this a stab. Assign me to the issue @thomashoneyman.

**Comment by thomashoneyman** [comment]
I'm only able to assign to repo members, but please feel free to take it!

**Comment by triallax** [comment]
> I'm only able to assign to repo members

That's a first for me.
Anyway, I'll hopefully fix it!

**Comment by thomashoneyman** [comment]
Well, I don’t know what I was doing wrong before, but I tried assigning to you again and this time your name did show up in the list. Assigned!

**Comment by triallax** [comment]
I have a question. What should I do when the latest release is a pre-release one? I know I'm supposed to find the latest release that's not a pre-release. How can I do that? Also, there is an edge case if the library only has pre-releases. What should we do in that case?

**Comment by thomashoneyman** [comment]
We already have the latest versions for each of the tools included in this repo, so I would say if there’s not a prerelease version then we can fall back to that.

And because we know what tools are supported we don’t have to worry about tools with only prerelease versions. That case won’t happen.

**Comment by triallax** [comment]
That makes sense. Are there any plans to change that versioning model? And if we control the latest versions, is there really any need for this check, or is it just in case?

**Comment by triallax** [comment]
Oh wait, it checks if the latest version in the GitHub repo is a prerelease, not the local version. Anyway, PR coming up soon.
