### ISSUE TITLE
Add possibility to specify a different repo for tool versions

### ISSUE THREAD

**Issue by i-am-the-slime** [purescript-contrib/setup-purescript#25]
I would like to use this: https://github.com/working-group-purescript-es/purescript/releases/tag/v0.15.0-alpha
But I think the repo is hardcoded, right?

**Comment by thomashoneyman** [comment]
Here's the current list of possible inputs:
https://github.com/purescript-contrib/setup-purescript/blob/main/action.yml

Perhaps we could change the `version` key so it accepts more than `latest` or a SemVer version. Instead, it could accept `latest`, a SemVer version, a Git tag, or a full URL like the one you specified and attempts to download it based on how it's parsed. We'd need to write a `string-parsers` parser for it.
