### ISSUE TITLE
Add ability to depend on latest PureScript release candidate via "unstable" version

### ISSUE THREAD

**Issue by JordanMartinez** [purescript-contrib/setup-purescript#26]
Since `setup-purescript` is used across core, contrib, web, and node, we'll need a way for CI to use the latest release candidate when migrating to `v0.15.0`.

Changing the version to 'unstable' for PureScript should select the latest release candidate, so we don't have to update it again if a new release candidate is made.

**Comment by thomashoneyman** [comment]
#25 is related as well
