### ISSUE TITLE
Split out bindings to GitHub Actions toolkit as a new library

### ISSUE THREAD

**Issue by thomashoneyman** [purescript-contrib/setup-purescript#4]
The core of this library is built on top of the [GitHub Actions toolkit](https://github.com/actions/toolkit), a set of libraries for executing commands within GitHub Actions. It is likely that others will want to write GitHub Actions in PureScript in the future, and these bindings are broadly useful outside this library.

Some possible actions that come to mind which could use this shared base:

1. Automatically format code using `purty` 
2. Automated attempts to upgrade package sets / dependencies in PureScript repositories
3. Automatically upload Pursuit documentation for releases which haven't been uploaded yet

All of the `Actions*` modules that exist in this library can be moved directly out to another package that exposes something like a set of modules named:

```
GitHub.Actions.ToolCache
GitHub.Actions.Cache
GitHub.Actions.GitHub
GitHub.Actions.IO
GitHub.Actions.Exec
...
```

which mirror the packages available in the official toolkit. The bindings weren't difficult to put together in the first place, so this shouldn't be more than a few hours' effort to set up.

**Comment by colinwahl** [comment]
I talked about this a bit with @thomashoneyman, and I've started work on it.
